# This is a basic workflow that is manually triggered

name: OpenAPI DIff Tool

# on:
#   pull_request:
#     types:
#       - opened
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: master
        path: main
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir spec && cp target/openapi.json spec/openapi-base.json
    
    - uses: actions/upload-artifact@v2
      with:
        name: openapi-base
        path: spec/openapi-base.json

  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: branch
    needs: build1
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: feature-apidiff-3
        path: branch

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir spec && cp target/openapi.json spec/openapi-revision.json
    
    - uses: actions/upload-artifact@v2
      with:
        name: openapi-revision
        path: spec/openapi-revision.json
  
  build3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build1, build2]
   
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: openapi-base
    - uses: actions/download-artifact@v2
      with:
        name: openapi-revision
    - name: Running OpenAPI Spec diff action
      id: test_breaking_changes
      uses: Tufin/oasdiff-action@v2
      with:
        base: 'openapi-base.json'
        revision: 'openapi-revision.json'
        format: 'text'
        breaking-only: true
        fail-on-diff: true
