name: OpenAPI DIff Tool

on:
  pull_request:
    types:
      - opened
# on:
#   workflow_dispatch:

jobs:
  api-diff-check:
    runs-on: ubuntu-latest

    steps:

    - name: Check out master branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: cp target/openapi.json openapi-base.json
    
    - name: Upload API Spec (Base)
      uses: actions/upload-artifact@v3
      with:
        name: openapi-base
        path: openapi-base.json

    - name: Check out PR branch
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: cp target/openapi.json openapi-revision.json
    
#     - name: Upload API Spec (Revision)
#       uses: actions/upload-artifact@v3
#       with:
#         name: openapi-revision
#         path: openapi-revision.json
    
    - name: Download API Spec (Base)
      uses: actions/download-artifact@v3
      with:
        name: openapi-base
#     - uses: actions/download-artifact@v3
#       with:
#         name: openapi-revision
        
    - name: Running OpenAPI Spec diff action
      id: test_breaking_changes
      uses: Tufin/oasdiff-action@v2
      with:
        base: 'openapi-base.json'
        revision: 'openapi-revision.json'
        format: 'text'
        breaking-only: true
        fail-on-diff: true
