# This is a basic workflow that is manually triggered

name: OpenAPI DIff Tool

on:
  pull_request:
    types:
      - opened
# on:
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: master
        path: main
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
 #   - run: cd main
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir spec && cp target/openapi.json spec
#    - run: cd ..
    
    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: branch
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
#    - run: cd branch
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir spec && cp target/openapi.json spec
    
    - name: Running OpenAPI Spec diff action
      id: test_breaking_changes
      uses: Tufin/oasdiff-action@v2
      with:
        base: 'main/spec/openapi.json'
        revision: 'branch/spec/openapi.json'
        format: 'text'
        breaking-only: true
        fail-on-diff: true
